# Generated by Django 5.2 on 2025-04-28 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.AutoField(help_text='ID único de la habitación', primary_key=True, serialize=False)),
                ('num_hab', models.CharField(help_text='Número de habitación', max_length=10, unique=True)),
                ('tipo', models.CharField(help_text='Tipo de habitación (sencilla, doble, suite, etc.)', max_length=50)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la habitación', null=True)),
                ('precio_por_noche', models.DecimalField(decimal_places=2, help_text='Precio por noche', max_digits=8)),
                ('estado', models.CharField(default='activo', help_text='Estado (activo/inactivo)', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(help_text='ID único del usuario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre completo', max_length=150)),
                ('correo', models.EmailField(help_text='Correo electrónico único', max_length=254, unique=True)),
                ('contraseña', models.CharField(help_text='Contraseña encriptada', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(help_text='ID único de la reserva', primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio de la reserva')),
                ('fecha_fin', models.DateField(help_text='Fecha de fin de la reserva')),
                ('estado_reserva', models.CharField(default='pendiente', help_text='Estado de la reserva (pendiente, confirmada, cancelada)', max_length=20)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_hotel.habitacion', verbose_name='Habitación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_hotel.usuario', verbose_name='Usuario')),
            ],
        ),
    ]
